// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp1.DataBase.Entity;

#nullable disable

namespace WpfApp1.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20260219171748_AddAxle")]
    partial class AddAxle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("WpfApp1.DataBase.Entity.Axle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrakeType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarModelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasParkingBrake")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasRegulator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RotationDirection")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId", "Order")
                        .IsUnique();

                    b.ToTable("Axles");
                });

            modelBuilder.Entity("WpfApp1.DataBase.Entity.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarBrands");
                });

            modelBuilder.Entity("WpfApp1.DataBase.Entity.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrakeForceDifference")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarBrandId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurbMass")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxMass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParkingBrake")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReserveBrake")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarBrandId");

                    b.HasIndex("CarCategoryId");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("WpfApp1.DataBase.Entity.CarСategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarСategories");
                });

            modelBuilder.Entity("WpfApp1.DataBase.Entity.DataCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("DataChecks");
                });

            modelBuilder.Entity("WpfApp1.DataBase.Entity.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("WpfApp1.DataBase.Entity.TheCar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GosNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VinCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.HasIndex("OwnerId");

                    b.ToTable("TheCars");
                });

            modelBuilder.Entity("WpfApp1.DataBase.Entity.Axle", b =>
                {
                    b.HasOne("WpfApp1.DataBase.Entity.CarModel", "CarModel")
                        .WithMany("Axles")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("WpfApp1.DataBase.Entity.CarModel", b =>
                {
                    b.HasOne("WpfApp1.DataBase.Entity.CarBrand", "CarBrand")
                        .WithMany("CarModels")
                        .HasForeignKey("CarBrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WpfApp1.DataBase.Entity.CarСategory", "CarСategory")
                        .WithMany("CarModels")
                        .HasForeignKey("CarCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CarBrand");

                    b.Navigation("CarСategory");
                });

            modelBuilder.Entity("WpfApp1.DataBase.Entity.DataCheck", b =>
                {
                    b.HasOne("WpfApp1.DataBase.Entity.Owner", "Owner")
                        .WithMany("DataChecks")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WpfApp1.DataBase.Entity.TheCar", b =>
                {
                    b.HasOne("WpfApp1.DataBase.Entity.CarModel", "CarModel")
                        .WithMany("TheCars")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WpfApp1.DataBase.Entity.Owner", "Owner")
                        .WithMany("TheCars")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WpfApp1.DataBase.Entity.CarBrand", b =>
                {
                    b.Navigation("CarModels");
                });

            modelBuilder.Entity("WpfApp1.DataBase.Entity.CarModel", b =>
                {
                    b.Navigation("Axles");

                    b.Navigation("TheCars");
                });

            modelBuilder.Entity("WpfApp1.DataBase.Entity.CarСategory", b =>
                {
                    b.Navigation("CarModels");
                });

            modelBuilder.Entity("WpfApp1.DataBase.Entity.Owner", b =>
                {
                    b.Navigation("DataChecks");

                    b.Navigation("TheCars");
                });
#pragma warning restore 612, 618
        }
    }
}
