// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechSto.DataBase.Entity;

#nullable disable

namespace TechSto.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("TechSto.DataBase.Entity.Axle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrakeType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarModelId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasParkingBrake")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasRegulator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RotationDirection")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId", "Order")
                        .IsUnique();

                    b.ToTable("Axles");
                });

            modelBuilder.Entity("TechSto.DataBase.Entity.CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarBrands");
                });

            modelBuilder.Entity("TechSto.DataBase.Entity.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BrakeForceDifference")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarBrandId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurbMass")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxMass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParkingBrake")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReserveBrake")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarBrandId");

                    b.HasIndex("CarCategoryId");

                    b.ToTable("CarModels");
                });

            modelBuilder.Entity("TechSto.DataBase.Entity.CarСategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarСategories");
                });

            modelBuilder.Entity("TechSto.DataBase.Entity.Check", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarMileage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CheckResult")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TheCarId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TheCarId");

                    b.ToTable("Checks");
                });

            modelBuilder.Entity("TechSto.DataBase.Entity.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("STSNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("TechSto.DataBase.Entity.TheCar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CarModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrameNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GosNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CarModelId");

                    b.HasIndex("OwnerId");

                    b.ToTable("TheCars");
                });

            modelBuilder.Entity("TechSto.DataBase.Entity.Axle", b =>
                {
                    b.HasOne("TechSto.DataBase.Entity.CarModel", "CarModel")
                        .WithMany("Axles")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("TechSto.DataBase.Entity.CarModel", b =>
                {
                    b.HasOne("TechSto.DataBase.Entity.CarBrand", "CarBrand")
                        .WithMany("CarModels")
                        .HasForeignKey("CarBrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TechSto.DataBase.Entity.CarСategory", "CarСategory")
                        .WithMany("CarModels")
                        .HasForeignKey("CarCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CarBrand");

                    b.Navigation("CarСategory");
                });

            modelBuilder.Entity("TechSto.DataBase.Entity.Check", b =>
                {
                    b.HasOne("TechSto.DataBase.Entity.TheCar", "TheCar")
                        .WithMany("DataChecks")
                        .HasForeignKey("TheCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TheCar");
                });

            modelBuilder.Entity("TechSto.DataBase.Entity.TheCar", b =>
                {
                    b.HasOne("TechSto.DataBase.Entity.CarModel", "CarModel")
                        .WithMany("TheCars")
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechSto.DataBase.Entity.Owner", "Owner")
                        .WithMany("TheCars")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarModel");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TechSto.DataBase.Entity.CarBrand", b =>
                {
                    b.Navigation("CarModels");
                });

            modelBuilder.Entity("TechSto.DataBase.Entity.CarModel", b =>
                {
                    b.Navigation("Axles");

                    b.Navigation("TheCars");
                });

            modelBuilder.Entity("TechSto.DataBase.Entity.CarСategory", b =>
                {
                    b.Navigation("CarModels");
                });

            modelBuilder.Entity("TechSto.DataBase.Entity.Owner", b =>
                {
                    b.Navigation("TheCars");
                });

            modelBuilder.Entity("TechSto.DataBase.Entity.TheCar", b =>
                {
                    b.Navigation("DataChecks");
                });
#pragma warning restore 612, 618
        }
    }
}
