//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechSto.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechSto.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AddClientWindowTitle {
            get { return ResourceManager.GetString("AddClientWindowTitle", resourceCulture); }
        }
        public static string SectionOwner {
            get { return ResourceManager.GetString("SectionOwner", resourceCulture); }
        }
        public static string SectionCar {
            get { return ResourceManager.GetString("SectionCar", resourceCulture); }
        }
        public static string SectionNewModel {
            get { return ResourceManager.GetString("SectionNewModel", resourceCulture); }
        }
        public static string NewOwner {
            get { return ResourceManager.GetString("NewOwner", resourceCulture); }
        }
        public static string ExistingOwner {
            get { return ResourceManager.GetString("ExistingOwner", resourceCulture); }
        }
        public static string OwnerNameLabel {
            get { return ResourceManager.GetString("OwnerNameLabel", resourceCulture); }
        }
        public static string StsNumberLabel {
            get { return ResourceManager.GetString("StsNumberLabel", resourceCulture); }
        }
        public static string GosNumberLabel {
            get { return ResourceManager.GetString("GosNumberLabel", resourceCulture); }
        }
        public static string VinNumberLabel {
            get { return ResourceManager.GetString("VinNumberLabel", resourceCulture); }
        }
        public static string ModelLabel {
            get { return ResourceManager.GetString("ModelLabel", resourceCulture); }
        }
        public static string NewModelBtn {
            get { return ResourceManager.GetString("NewModelBtn", resourceCulture); }
        }
        public static string BrandLabel {
            get { return ResourceManager.GetString("BrandLabel", resourceCulture); }
        }
        public static string NewBrandBtn {
            get { return ResourceManager.GetString("NewBrandBtn", resourceCulture); }
        }
        public static string BrandNameLabel {
            get { return ResourceManager.GetString("BrandNameLabel", resourceCulture); }
        }
        public static string CategoryLabel {
            get { return ResourceManager.GetString("CategoryLabel", resourceCulture); }
        }
        public static string MaxMassLabel {
            get { return ResourceManager.GetString("MaxMassLabel", resourceCulture); }
        }
        public static string CurbMassLabel {
            get { return ResourceManager.GetString("CurbMassLabel", resourceCulture); }
        }
        public static string BrakeDiffLabel {
            get { return ResourceManager.GetString("BrakeDiffLabel", resourceCulture); }
        }
        public static string ParkingBrakeLabel {
            get { return ResourceManager.GetString("ParkingBrakeLabel", resourceCulture); }
        }
        public static string ReserveBrakeLabel {
            get { return ResourceManager.GetString("ReserveBrakeLabel", resourceCulture); }
        }
        public static string AxleCountLabel {
            get { return ResourceManager.GetString("AxleCountLabel", resourceCulture); }
        }
        public static string AxleDirection {
            get { return ResourceManager.GetString("AxleDirection", resourceCulture); }
        }
        public static string AxleParkingBrake {
            get { return ResourceManager.GetString("AxleParkingBrake", resourceCulture); }
        }
        public static string AxleBrakeType {
            get { return ResourceManager.GetString("AxleBrakeType", resourceCulture); }
        }
        public static string AxleRegulator {
            get { return ResourceManager.GetString("AxleRegulator", resourceCulture); }
        }
        public static string CreateModelBtn {
            get { return ResourceManager.GetString("CreateModelBtn", resourceCulture); }
        }
        public static string CreateBrandBtn {
            get { return ResourceManager.GetString("CreateBrandBtn", resourceCulture); }
        }
        public static string AddAnotherCarBtn {
            get { return ResourceManager.GetString("AddAnotherCarBtn", resourceCulture); }
        }
        public static string SaveAllBtn {
            get { return ResourceManager.GetString("SaveAllBtn", resourceCulture); }
        }
        public static string ColOwner {
            get { return ResourceManager.GetString("ColOwner", resourceCulture); }
        }
        public static string ColStateNumber {
            get { return ResourceManager.GetString("ColStateNumber", resourceCulture); }
        }
        public static string ColVin {
            get { return ResourceManager.GetString("ColVin", resourceCulture); }
        }
        public static string ColBrand {
            get { return ResourceManager.GetString("ColBrand", resourceCulture); }
        }
        public static string ColModel {
            get { return ResourceManager.GetString("ColModel", resourceCulture); }
        }
        public static string ColLastTest {
            get { return ResourceManager.GetString("ColLastTest", resourceCulture); }
        }
        public static string ErrorTitle {
            get { return ResourceManager.GetString("ErrorTitle", resourceCulture); }
        }
        public static string ConfirmTitle {
            get { return ResourceManager.GetString("ConfirmTitle", resourceCulture); }
        }
        public static string ErrorLoadData {
            get { return ResourceManager.GetString("ErrorLoadData", resourceCulture); }
        }
        public static string WarnEnterBrandName {
            get { return ResourceManager.GetString("WarnEnterBrandName", resourceCulture); }
        }
        public static string WarnEnterModelName {
            get { return ResourceManager.GetString("WarnEnterModelName", resourceCulture); }
        }
        public static string WarnSelectBrand {
            get { return ResourceManager.GetString("WarnSelectBrand", resourceCulture); }
        }
        public static string ErrorCreateModel {
            get { return ResourceManager.GetString("ErrorCreateModel", resourceCulture); }
        }
        public static string WarnEnterGosNumber {
            get { return ResourceManager.GetString("WarnEnterGosNumber", resourceCulture); }
        }
        public static string WarnSelectCarModel {
            get { return ResourceManager.GetString("WarnSelectCarModel", resourceCulture); }
        }
        public static string WarnEnterOwnerName {
            get { return ResourceManager.GetString("WarnEnterOwnerName", resourceCulture); }
        }
        public static string WarnSelectOwner {
            get { return ResourceManager.GetString("WarnSelectOwner", resourceCulture); }
        }
        public static string WarnAddAtLeastOneCar {
            get { return ResourceManager.GetString("WarnAddAtLeastOneCar", resourceCulture); }
        }
        public static string ErrorSaveData {
            get { return ResourceManager.GetString("ErrorSaveData", resourceCulture); }
        }
        public static string ErrorCarNotFound {
            get { return ResourceManager.GetString("ErrorCarNotFound", resourceCulture); }
        }
        public static string ErrorWindowInit {
            get { return ResourceManager.GetString("ErrorWindowInit", resourceCulture); }
        }
        public static string ErrorLanguageSwitch {
            get { return ResourceManager.GetString("ErrorLanguageSwitch", resourceCulture); }
        }
        public static string WarnSelectRowToEdit {
            get { return ResourceManager.GetString("WarnSelectRowToEdit", resourceCulture); }
        }
        public static string WarnSelectRowToDelete {
            get { return ResourceManager.GetString("WarnSelectRowToDelete", resourceCulture); }
        }
        public static string ConfirmDeleteCar {
            get { return ResourceManager.GetString("ConfirmDeleteCar", resourceCulture); }
        }
        public static string PreviewSectionOwner {
            get { return ResourceManager.GetString("PreviewSectionOwner", resourceCulture); }
        }
        public static string PreviewOwnerName {
            get { return ResourceManager.GetString("PreviewOwnerName", resourceCulture); }
        }
        public static string PreviewOwnerSts {
            get { return ResourceManager.GetString("PreviewOwnerSts", resourceCulture); }
        }
        public static string PreviewSectionCar {
            get { return ResourceManager.GetString("PreviewSectionCar", resourceCulture); }
        }
        public static string PreviewCarGos {
            get { return ResourceManager.GetString("PreviewCarGos", resourceCulture); }
        }
        public static string PreviewCarVin {
            get { return ResourceManager.GetString("PreviewCarVin", resourceCulture); }
        }
        public static string PreviewCarBrand {
            get { return ResourceManager.GetString("PreviewCarBrand", resourceCulture); }
        }
        public static string PreviewCarModel {
            get { return ResourceManager.GetString("PreviewCarModel", resourceCulture); }
        }
        public static string PreviewSectionSpecs {
            get { return ResourceManager.GetString("PreviewSectionSpecs", resourceCulture); }
        }
        public static string PreviewCategory {
            get { return ResourceManager.GetString("PreviewCategory", resourceCulture); }
        }
        public static string PreviewMaxMass {
            get { return ResourceManager.GetString("PreviewMaxMass", resourceCulture); }
        }
        public static string PreviewCurbMass {
            get { return ResourceManager.GetString("PreviewCurbMass", resourceCulture); }
        }
        public static string PreviewBrakeDiff {
            get { return ResourceManager.GetString("PreviewBrakeDiff", resourceCulture); }
        }
        public static string PreviewParkingBrake {
            get { return ResourceManager.GetString("PreviewParkingBrake", resourceCulture); }
        }
        public static string PreviewReserveBrake {
            get { return ResourceManager.GetString("PreviewReserveBrake", resourceCulture); }
        }
        public static string PreviewSectionAxles {
            get { return ResourceManager.GetString("PreviewSectionAxles", resourceCulture); }
        }
        public static string PreviewLastCheck {
            get { return ResourceManager.GetString("PreviewLastCheck", resourceCulture); }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string AddBth {
            get {
                return ResourceManager.GetString("AddBth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление брендами.
        /// </summary>
        public static string BrandsWindowTitle {
            get {
                return ResourceManager.GetString("BrandsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать.
        /// </summary>
        public static string ChooseBtn {
            get {
                return ResourceManager.GetString("ChooseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string DeleteBth {
            get {
                return ResourceManager.GetString("DeleteBth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить выбранный элемент?.
        /// </summary>
        public static string DeleteSelectedItem {
            get {
                return ResourceManager.GetString("DeleteSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название..
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измерения.
        /// </summary>
        public static string Measurements {
            get {
                return ResourceManager.GetString("Measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        public static string MessageWarning {
            get {
                return ResourceManager.GetString("MessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string NameElement {
            get {
                return ResourceManager.GetString("NameElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТехСто - Программа проверки тормозных усилий.
        /// </summary>
        public static string NameProgram {
            get {
                return ResourceManager.GetString("NameProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчеты.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо выбрать марку машины..
        /// </summary>
        public static string SelectItemToChoose {
            get {
                return ResourceManager.GetString("SelectItemToChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите элемент для удаления..
        /// </summary>
        public static string SelectItemToDelete {
            get {
                return ResourceManager.GetString("SelectItemToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите элемент для редактирования..
        /// </summary>
        public static string SelectItemToEdit {
            get {
                return ResourceManager.GetString("SelectItemToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        public static string UpdateBth {
            get {
                return ResourceManager.GetString("UpdateBth", resourceCulture);
            }
        }
    }
}
