//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechSto.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechSto.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить ещё автомобиль.
        /// </summary>
        public static string AddAnotherCarBtn {
            get {
                return ResourceManager.GetString("AddAnotherCarBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string AddBth {
            get {
                return ResourceManager.GetString("AddBth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление клиента и автомобиля.
        /// </summary>
        public static string AddClientWindowTitle {
            get {
                return ResourceManager.GetString("AddClientWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип тормоза.
        /// </summary>
        public static string AxleBrakeType {
            get {
                return ResourceManager.GetString("AxleBrakeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во осей.
        /// </summary>
        public static string AxleCountLabel {
            get {
                return ResourceManager.GetString("AxleCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Направление.
        /// </summary>
        public static string AxleDirection {
            get {
                return ResourceManager.GetString("AxleDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стояночн..
        /// </summary>
        public static string AxleParkingBrake {
            get {
                return ResourceManager.GetString("AxleParkingBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регулятор.
        /// </summary>
        public static string AxleRegulator {
            get {
                return ResourceManager.GetString("AxleRegulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разница торм. усилия.
        /// </summary>
        public static string BrakeDiffLabel {
            get {
                return ResourceManager.GetString("BrakeDiffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Марка.
        /// </summary>
        public static string BrandLabel {
            get {
                return ResourceManager.GetString("BrandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название марки.
        /// </summary>
        public static string BrandNameLabel {
            get {
                return ResourceManager.GetString("BrandNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление брендами.
        /// </summary>
        public static string BrandsWindowTitle {
            get {
                return ResourceManager.GetString("BrandsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория.
        /// </summary>
        public static string CategoryLabel {
            get {
                return ResourceManager.GetString("CategoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать.
        /// </summary>
        public static string ChooseBtn {
            get {
                return ResourceManager.GetString("ChooseBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Марка.
        /// </summary>
        public static string ColBrand {
            get {
                return ResourceManager.GetString("ColBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата последнего испытания.
        /// </summary>
        public static string ColLastTest {
            get {
                return ResourceManager.GetString("ColLastTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель.
        /// </summary>
        public static string ColModel {
            get {
                return ResourceManager.GetString("ColModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Владелец.
        /// </summary>
        public static string ColOwner {
            get {
                return ResourceManager.GetString("ColOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гос номер.
        /// </summary>
        public static string ColStateNumber {
            get {
                return ResourceManager.GetString("ColStateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VIN номер.
        /// </summary>
        public static string ColVin {
            get {
                return ResourceManager.GetString("ColVin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить автомобиль {0}?.
        /// </summary>
        public static string ConfirmDeleteCar {
            get {
                return ResourceManager.GetString("ConfirmDeleteCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение.
        /// </summary>
        public static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать марку.
        /// </summary>
        public static string CreateBrandBtn {
            get {
                return ResourceManager.GetString("CreateBrandBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать модель.
        /// </summary>
        public static string CreateModelBtn {
            get {
                return ResourceManager.GetString("CreateModelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Снаряж. масса (кг).
        /// </summary>
        public static string CurbMassLabel {
            get {
                return ResourceManager.GetString("CurbMassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string DeleteBth {
            get {
                return ResourceManager.GetString("DeleteBth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить выбранный элемент?.
        /// </summary>
        public static string DeleteSelectedItem {
            get {
                return ResourceManager.GetString("DeleteSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название..
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стенд подключен.
        /// </summary>
        public static string EquipmentIsConnected {
            get {
                return ResourceManager.GetString("EquipmentIsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стенд не подключен.
        /// </summary>
        public static string EquipmentIsNotConnected {
            get {
                return ResourceManager.GetString("EquipmentIsNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автомобиль не найден..
        /// </summary>
        public static string ErrorCarNotFound {
            get {
                return ResourceManager.GetString("ErrorCarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при создании модели: {0}.
        /// </summary>
        public static string ErrorCreateModel {
            get {
                return ResourceManager.GetString("ErrorCreateModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при смене языка: {0}.
        /// </summary>
        public static string ErrorLanguageSwitch {
            get {
                return ResourceManager.GetString("ErrorLanguageSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки данных: {0}.
        /// </summary>
        public static string ErrorLoadData {
            get {
                return ResourceManager.GetString("ErrorLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при сохранении: {0}.
        /// </summary>
        public static string ErrorSaveData {
            get {
                return ResourceManager.GetString("ErrorSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при инициализации окна: {0}.
        /// </summary>
        public static string ErrorWindowInit {
            get {
                return ResourceManager.GetString("ErrorWindowInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать существующего.
        /// </summary>
        public static string ExistingOwner {
            get {
                return ResourceManager.GetString("ExistingOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Госномер.
        /// </summary>
        public static string GosNumberLabel {
            get {
                return ResourceManager.GetString("GosNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макс. масса (кг).
        /// </summary>
        public static string MaxMassLabel {
            get {
                return ResourceManager.GetString("MaxMassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Измерения.
        /// </summary>
        public static string Measurements {
            get {
                return ResourceManager.GetString("Measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        public static string MessageWarning {
            get {
                return ResourceManager.GetString("MessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель.
        /// </summary>
        public static string ModelLabel {
            get {
                return ResourceManager.GetString("ModelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string NameElement {
            get {
                return ResourceManager.GetString("NameElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТехСто - Программа проверки тормозных усилий.
        /// </summary>
        public static string NameProgram {
            get {
                return ResourceManager.GetString("NameProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая марка.
        /// </summary>
        public static string NewBrandBtn {
            get {
                return ResourceManager.GetString("NewBrandBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая модель.
        /// </summary>
        public static string NewModelBtn {
            get {
                return ResourceManager.GetString("NewModelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый.
        /// </summary>
        public static string NewOwner {
            get {
                return ResourceManager.GetString("NewOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string OwnerNameLabel {
            get {
                return ResourceManager.GetString("OwnerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стояночный тормоз.
        /// </summary>
        public static string ParkingBrakeLabel {
            get {
                return ResourceManager.GetString("ParkingBrakeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разн. торм.:.
        /// </summary>
        public static string PreviewBrakeDiff {
            get {
                return ResourceManager.GetString("PreviewBrakeDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Марка:.
        /// </summary>
        public static string PreviewCarBrand {
            get {
                return ResourceManager.GetString("PreviewCarBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Госномер:.
        /// </summary>
        public static string PreviewCarGos {
            get {
                return ResourceManager.GetString("PreviewCarGos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель:.
        /// </summary>
        public static string PreviewCarModel {
            get {
                return ResourceManager.GetString("PreviewCarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VIN:.
        /// </summary>
        public static string PreviewCarVin {
            get {
                return ResourceManager.GetString("PreviewCarVin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория:.
        /// </summary>
        public static string PreviewCategory {
            get {
                return ResourceManager.GetString("PreviewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Снаряж. масса:.
        /// </summary>
        public static string PreviewCurbMass {
            get {
                return ResourceManager.GetString("PreviewCurbMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последняя проверка:.
        /// </summary>
        public static string PreviewLastCheck {
            get {
                return ResourceManager.GetString("PreviewLastCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Макс. масса:.
        /// </summary>
        public static string PreviewMaxMass {
            get {
                return ResourceManager.GetString("PreviewMaxMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя:.
        /// </summary>
        public static string PreviewOwnerName {
            get {
                return ResourceManager.GetString("PreviewOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СТС:.
        /// </summary>
        public static string PreviewOwnerSts {
            get {
                return ResourceManager.GetString("PreviewOwnerSts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стояночный:.
        /// </summary>
        public static string PreviewParkingBrake {
            get {
                return ResourceManager.GetString("PreviewParkingBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резервный:.
        /// </summary>
        public static string PreviewReserveBrake {
            get {
                return ResourceManager.GetString("PreviewReserveBrake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оси.
        /// </summary>
        public static string PreviewSectionAxles {
            get {
                return ResourceManager.GetString("PreviewSectionAxles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автомобиль.
        /// </summary>
        public static string PreviewSectionCar {
            get {
                return ResourceManager.GetString("PreviewSectionCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Владелец.
        /// </summary>
        public static string PreviewSectionOwner {
            get {
                return ResourceManager.GetString("PreviewSectionOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Характеристики.
        /// </summary>
        public static string PreviewSectionSpecs {
            get {
                return ResourceManager.GetString("PreviewSectionSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчеты.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резервный тормоз.
        /// </summary>
        public static string ReserveBrakeLabel {
            get {
                return ResourceManager.GetString("ReserveBrakeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string SaveAllBtn {
            get {
                return ResourceManager.GetString("SaveAllBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автомобиль.
        /// </summary>
        public static string SectionCar {
            get {
                return ResourceManager.GetString("SectionCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание новой модели.
        /// </summary>
        public static string SectionNewModel {
            get {
                return ResourceManager.GetString("SectionNewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Владелец.
        /// </summary>
        public static string SectionOwner {
            get {
                return ResourceManager.GetString("SectionOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо выбрать марку машины..
        /// </summary>
        public static string SelectItemToChoose {
            get {
                return ResourceManager.GetString("SelectItemToChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите элемент для удаления..
        /// </summary>
        public static string SelectItemToDelete {
            get {
                return ResourceManager.GetString("SelectItemToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите элемент для редактирования..
        /// </summary>
        public static string SelectItemToEdit {
            get {
                return ResourceManager.GetString("SelectItemToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установки.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер СТС.
        /// </summary>
        public static string StsNumberLabel {
            get {
                return ResourceManager.GetString("StsNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        public static string UpdateBth {
            get {
                return ResourceManager.GetString("UpdateBth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на VIN номер.
        /// </summary>
        public static string VinNumberLabel {
            get {
                return ResourceManager.GetString("VinNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте хотя бы один автомобиль..
        /// </summary>
        public static string WarnAddAtLeastOneCar {
            get {
                return ResourceManager.GetString("WarnAddAtLeastOneCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название марки..
        /// </summary>
        public static string WarnEnterBrandName {
            get {
                return ResourceManager.GetString("WarnEnterBrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите госномер..
        /// </summary>
        public static string WarnEnterGosNumber {
            get {
                return ResourceManager.GetString("WarnEnterGosNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название модели..
        /// </summary>
        public static string WarnEnterModelName {
            get {
                return ResourceManager.GetString("WarnEnterModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя владельца..
        /// </summary>
        public static string WarnEnterOwnerName {
            get {
                return ResourceManager.GetString("WarnEnterOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите марку..
        /// </summary>
        public static string WarnSelectBrand {
            get {
                return ResourceManager.GetString("WarnSelectBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите модель автомобиля..
        /// </summary>
        public static string WarnSelectCarModel {
            get {
                return ResourceManager.GetString("WarnSelectCarModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите владельца из списка..
        /// </summary>
        public static string WarnSelectOwner {
            get {
                return ResourceManager.GetString("WarnSelectOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите строку для удаления..
        /// </summary>
        public static string WarnSelectRowToDelete {
            get {
                return ResourceManager.GetString("WarnSelectRowToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите строку для редактирования..
        /// </summary>
        public static string WarnSelectRowToEdit {
            get {
                return ResourceManager.GetString("WarnSelectRowToEdit", resourceCulture);
            }
        }
    }
}
